services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    volumes:
      - mongo_data:/data/db
  api:
    build: .
    env_file: .env
    ports:
      - "3001:3001"
    depends_on:
      - mongo
volumes:
  mongo_data:
